FROM dunglas/frankenphp:1-php8.4

RUN apt-get update && apt-get install -y \
    supervisor \
    && rm -rf /var/lib/apt/lists/*

RUN install-php-extensions \
    pdo_pgsql \
    pdo_sqlite \
    redis \
    gd \
    zip \
    pcntl \
    opcache \
    mbstring \
    bcmath \
    intl

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /code

COPY composer.json composer.lock ./
RUN composer install --no-dev --no-scripts --optimize-autoloader

COPY . .

RUN mkdir -p /var/log/supervisor /var/run

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY custom-php.ini /usr/local/etc/php/conf.d/custom-php.ini

EXPOSE 9000 8006

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
